"""empty message

Revision ID: 364e0ab117f2
Revises: 33616191117b
Create Date: 2022-08-12 16:17:07.021446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364e0ab117f2'
down_revision = '33616191117b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'list_id')
    # ### end Alembic commands ###
